services:
  # ===== CORE : WireGuard VPN + SFTP Server + Restic Backup =====
  core:
    build:
      context: .
      dockerfile: services/core/Dockerfile
    container_name: anemone-core
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TIMEZONE:-Europe/Paris}
      - CONFIG_PATH=/config/config.yaml
    volumes:
      - ./config:/config
      - ${BACKUP_DATA_PATH:-./backup}:/mnt/backup
      - ${BACKUP_RECEIVE_PATH:-./backups}:/home/restic/backups
      - ./config-backups:/config-backups
      - ./logs:/logs
      - ./shared-stats:/var/stats  # Volume partagé pour les stats Restic
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"  # WireGuard VPN
      - "${SFTP_PORT:-22222}:22"  # SFTP for receiving backups
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
    networks:
      - anemone-net
    healthcheck:
      test: ["CMD", "sh", "-c", "wg show && ss -tlnp | grep -q ':22'"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ===== SHARES : Samba SMB + WebDAV (OPTIONNEL) =====
  shares:
    build:
      context: ./services/shares
      dockerfile: Dockerfile
    container_name: anemone-shares
    environment:
      - TZ=${TIMEZONE:-Europe/Paris}
      - SMB_USER=${SMB_USER:-anemone}
      - SMB_PASSWORD=${SMB_PASSWORD:-changeme}
      - SMB_WORKGROUP=${SMB_WORKGROUP:-WORKGROUP}
      - WEBDAV_USER=${WEBDAV_USER:-anemone}
      - WEBDAV_PASSWORD=${WEBDAV_PASSWORD:-changeme}
      - WEBDAV_PORT=${WEBDAV_PORT:-8080}
    volumes:
      - ${DATA_PATH:-./data}:/mnt/data
      - ${BACKUP_DATA_PATH:-./backup}:/mnt/backup
      - ./logs:/logs
    ports:
      - "445:445"        # Samba SMB
      - "139:139"        # Samba NetBIOS
      - "${WEBDAV_PORT:-8080}:${WEBDAV_PORT:-8080}"  # WebDAV
    restart: unless-stopped
    networks:
      - anemone-net
    profiles:
      - shares  # Ce service ne démarre que si le profile 'shares' est activé
    healthcheck:
      test: ["CMD", "sh", "-c", "smbclient -L localhost -U% > /dev/null 2>&1 && ss -tln | grep -q ':${WEBDAV_PORT:-8080}'"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ===== API : Interface Web =====
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    container_name: anemone-api
    environment:
      - CONFIG_PATH=/config/config.yaml
      - WEB_LANGUAGE=${WEB_LANGUAGE:-fr}
      - WEB_PASSWORD=${WEB_PASSWORD:-}
    volumes:
      - ./config:/config
      - ./logs:/logs:ro
      - ./scripts:/scripts:ro
      - ./shared-stats:/var/stats:ro  # Volume partagé pour les stats Restic (lecture seule)
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "${API_PORT:-3000}:3000"
    restart: unless-stopped
    depends_on:
      - core
    networks:
      - anemone-net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  anemone-net:
    driver: bridge
