# Anemone - Multi-user NAS with P2P encrypted synchronization
# Copyright (C) 2025 juste-un-gars
# Licensed under the GNU Affero General Public License v3.0

services:
  anemone:
    build: .
    container_name: anemone
    restart: unless-stopped
    ports:
      - "8080:8080"   # Web UI
      - "445:445"     # SMB
    volumes:
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ANEMONE_DATA_DIR=/app/data
      - PORT=8080
      - LANGUAGE=fr
      - TZ=Europe/Paris
    cap_add:
      - SYS_ADMIN    # Required for Samba
    networks:
      - anemone-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  anemone-net:
    driver: bridge
