# Anemone - Multi-user NAS with P2P encrypted synchronization
# Copyright (C) 2025 juste-un-gars
# Licensed under the GNU Affero General Public License v3.0

services:
  anemone:
    build: .
    container_name: anemone
    restart: unless-stopped
    ports:
      - "8443:8443"   # Web UI (HTTPS)
      - "8080:8080"   # Web UI (HTTP - disabled by default)
      - "445:445"     # SMB
    volumes:
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ANEMONE_DATA_DIR=/app/data
      - HTTPS_PORT=8443
      - PORT=8080
      - ENABLE_HTTPS=true
      - ENABLE_HTTP=false
      - LANGUAGE=fr
      - TZ=Europe/Paris
    cap_add:
      - SYS_ADMIN    # Required for Samba
    networks:
      - anemone-net
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -fk https://localhost:8443/health || curl -f http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  anemone-net:
    driver: bridge
